language: php

php:
  - 5.6

before_script:
  - cd api/services
  - composer self-update
  - composer install --no-interaction
  - sudo chmod -R 777 storage
  - sudo chmod -R 777 bootstrap
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e 'create database fast_quiz_test;'
  - php artisan migrate
  - php artisan db:seed
  

script:
  - vendor/bin/phpunit